from aiogram.fsm.state import State, StatesGroup


class BotStates(StatesGroup):
    menu = State()
    upload_category = State()
    upload_photos = State()
    wardrobe_view = State()
    request_occasion = State()
    request_season = State()
    generating = State()
    subscription = State()
    feedback_waiting_text = State()
    survey_waiting_text = State()
    manual_select_category = State()
    manual_select_subcategory = State()
    manual_select_color = State()
    manual_select_season = State()
    manual_select_formality = State()
    manual_enter_price = State()
    editing_price = State()
    search_mode = State()
    setting_city = State()
    check_compatibility = State()
    capsule_create_name = State()
